#!/bin/bash
#
#$ -cwd
#$ -j y
#$ -S /bin/bash
#$ -pe make 1

perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr10_part10_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr10_part1_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr10_part2_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr10_part3_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr10_part4_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr10_part5_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr10_part6_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr10_part7_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr10_part8_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr10_part9_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr1_part10_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr1_part11_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr1_part12_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr1_part13_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr1_part14_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr1_part1_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr1_part2_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr1_part3_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr1_part4_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr1_part5_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr1_part6_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr1_part7_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr1_part8_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr1_part9_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr2_part10_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr2_part11_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr2_part12_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr2_part13_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr2_part14_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr2_part15_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr2_part1_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr2_part2_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr2_part3_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr2_part4_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr2_part5_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr2_part6_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr2_part7_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr2_part8_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr2_part9_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr3_part1_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr3_part2_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr3_part3_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr3_part4_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr3_part5_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr3_part6_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr3_part7_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr3_part8_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr3_part9_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr4_part1_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr4_part2_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr4_part3_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr4_part4_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr4_part5_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr4_part6_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr4_part7_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr4_part8_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr5_part10_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr5_part11_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr5_part12_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr5_part13_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr5_part14_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr5_part15_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr5_part16_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr5_part17_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr5_part18_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr5_part19_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr5_part1_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr5_part2_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr5_part3_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr5_part4_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr5_part5_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr5_part6_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr5_part7_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr5_part8_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr5_part9_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr6_part1_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr6_part2_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr6_part3_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr6_part4_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr6_part5_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr6_part6_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr6_part7_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr7_part10_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr7_part11_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr7_part12_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr7_part13_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr7_part14_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr7_part1_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr7_part2_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr7_part3_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr7_part4_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr7_part5_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr7_part6_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr7_part7_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr7_part8_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr7_part9_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr8_part10_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr8_part11_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr8_part12_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr8_part13_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr8_part14_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr8_part15_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr8_part1_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr8_part2_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr8_part3_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr8_part4_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr8_part5_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr8_part6_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr8_part7_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr8_part8_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr8_part9_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr9_part10_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr9_part11_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr9_part12_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr9_part13_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr9_part14_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr9_part15_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr9_part1_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr9_part2_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr9_part3_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr9_part4_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr9_part5_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr9_part6_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr9_part7_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr9_part8_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  endo_chr9_part9_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr10_part1_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr1_part1_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr1_part2_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr1_part3_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr1_part4_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr1_part5_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr1_part6_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr1_part7_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr2_part10_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr2_part1_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr2_part2_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr2_part3_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr2_part4_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr2_part5_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr2_part6_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr2_part7_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr2_part8_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr2_part9_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr3_part10_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr3_part11_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr3_part12_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr3_part13_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr3_part1_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr3_part2_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr3_part3_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr3_part4_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr3_part5_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr3_part6_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr3_part7_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr3_part8_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr3_part9_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr4_part1_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr4_part2_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr4_part3_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr4_part4_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr4_part5_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr4_part6_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr4_part7_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr5_part10_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr5_part11_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr5_part1_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr5_part2_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr5_part3_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr5_part4_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr5_part5_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr5_part6_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr5_part7_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr5_part8_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr5_part9_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr6_part1_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr6_part2_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr6_part3_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr6_part4_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr6_part5_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr6_part6_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr7_part1_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr7_part2_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr7_part3_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr7_part4_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr8_part1_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr8_part2_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr8_part3_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr8_part4_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr8_part5_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr9_part1_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr9_part2_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr9_part3_modified
perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/matrix2compartment.pl -i  shoot_chr9_part4_modified
