library("backports")
library("FitHiC")


#setwd("/NAS1/huangliang/Hi-C/FIT_HIC_for_loops_calling/40kb_shoot_loops")
# fragsfile <- file.path(getwd(), "fithic.fragmentMappability")
# intersfile <-file.path(getwd(), "fithic.interactionCounts")
# biasfile <- file.path(getwd(), "fithic.biases")
# outdir <- file.path(getwd(), "FIT_HIC")
#FitHiC(fragsfile, intersfile, outdir, biasfile,libname="FIT_HIC", noOfBins=100,distUpThres=20000000, distLowThres=40000, visual=TRUE)
#setwd("/NAS1/huangliang/Hi-C/FIT_HIC_for_loops_calling/40kb_endo_loops")
# fragsfile <- file.path(getwd(), "fithic.fragmentMappability")
# intersfile <-file.path(getwd(), "fithic.interactionCounts")
# biasfile <- file.path(getwd(), "fithic.biases")
# outdir <- file.path(getwd(), "FIT_HIC")
#FitHiC(fragsfile, intersfile, outdir, biasfile,libname="FIT_HIC", noOfBins=100,distUpThres=20000000, distLowThres=40000, visual=TRUE)


#setwd("/NAS1/huangliang/Hi-C/FIT_HIC_for_loops_calling/25kb_shoot_loops")
# fragsfile <- file.path(getwd(), "fithic.fragmentMappability")
# intersfile <-file.path(getwd(), "fithic.interactionCounts")
# biasfile <- file.path(getwd(), "fithic.biases")
# outdir <- file.path(getwd(), "FIT_HIC")
#FitHiC(fragsfile, intersfile, outdir, biasfile,libname="FIT_HIC", noOfBins=100,distUpThres=20000000, distLowThres=25000, visual=TRUE)
#setwd("/NAS1/huangliang/Hi-C/FIT_HIC_for_loops_calling/25kb_endo_loops")
# fragsfile <- file.path(getwd(), "fithic.fragmentMappability")
# intersfile <-file.path(getwd(), "fithic.interactionCounts")
# biasfile <- file.path(getwd(), "fithic.biases")
# outdir <- file.path(getwd(), "FIT_HIC")
#FitHiC(fragsfile, intersfile, outdir, biasfile,libname="FIT_HIC", noOfBins=100,distUpThres=20000000, distLowThres=25000, visual=TRUE)


setwd("/NAS1/huangliang/Hi-C/FIT_HIC_for_loops_calling/20kb_shoot_loops")
 fragsfile <- file.path(getwd(), "fithic.fragmentMappability")
 intersfile <-file.path(getwd(), "fithic.interactionCounts")
 biasfile <- file.path(getwd(), "fithic.biases")
 outdir <- file.path(getwd(), "FIT_HIC")
FitHiC(fragsfile, intersfile, outdir, biasfile,libname="FIT_HIC", noOfBins=100,distUpThres=20000000, distLowThres=20000, visual=TRUE)
setwd("/NAS1/huangliang/Hi-C/FIT_HIC_for_loops_calling/20kb_endo_loops")
 fragsfile <- file.path(getwd(), "fithic.fragmentMappability")
 intersfile <-file.path(getwd(), "fithic.interactionCounts")
 biasfile <- file.path(getwd(), "fithic.biases")
 outdir <- file.path(getwd(), "FIT_HIC")
FitHiC(fragsfile, intersfile, outdir, biasfile,libname="FIT_HIC", noOfBins=100,distUpThres=20000000, distLowThres=20000, visual=TRUE)



setwd("/NAS1/huangliang/Hi-C/FIT_HIC_for_loops_calling/10kb_shoot_loops")
 fragsfile <- file.path(getwd(), "fithic.fragmentMappability")
 intersfile <-file.path(getwd(), "fithic.interactionCounts")
 biasfile <- file.path(getwd(), "fithic.biases")
 outdir <- file.path(getwd(), "FIT_HIC")
FitHiC(fragsfile, intersfile, outdir, biasfile,libname="FIT_HIC", noOfBins=100,distUpThres=20000000, distLowThres=10000, visual=TRUE)
setwd("/NAS1/huangliang/Hi-C/FIT_HIC_for_loops_calling/10kb_endo_loops")
 fragsfile <- file.path(getwd(), "fithic.fragmentMappability")
 intersfile <-file.path(getwd(), "fithic.interactionCounts")
 biasfile <- file.path(getwd(), "fithic.biases")
 outdir <- file.path(getwd(), "FIT_HIC")
FitHiC(fragsfile, intersfile, outdir, biasfile,libname="FIT_HIC", noOfBins=100,distUpThres=20000000, distLowThres=10000, visual=TRUE)

