source("TopDom_v0.0.2.R")
setwd("/NAS1/huangliang/Hi-C/TAD_file/endosperm/20000/")
  TopDom(matrix.file="/NAS1/huangliang/Hi-C/matrix_file/endosperm/20000/chr1.matrix",  window.size=10, outFile="chr1", statFilter=T)
  TopDom(matrix.file="/NAS1/huangliang/Hi-C/matrix_file/endosperm/20000/chr2.matrix",  window.size=10, outFile="chr2", statFilter=T)
  TopDom(matrix.file="/NAS1/huangliang/Hi-C/matrix_file/endosperm/20000/chr3.matrix",  window.size=10, outFile="chr3", statFilter=T)
  TopDom(matrix.file="/NAS1/huangliang/Hi-C/matrix_file/endosperm/20000/chr4.matrix",  window.size=10, outFile="chr4", statFilter=T)
  TopDom(matrix.file="/NAS1/huangliang/Hi-C/matrix_file/endosperm/20000/chr5.matrix",  window.size=10, outFile="chr5", statFilter=T)
  TopDom(matrix.file="/NAS1/huangliang/Hi-C/matrix_file/endosperm/20000/chr6.matrix",  window.size=10, outFile="chr6", statFilter=T)
  TopDom(matrix.file="/NAS1/huangliang/Hi-C/matrix_file/endosperm/20000/chr7.matrix",  window.size=10, outFile="chr7", statFilter=T)
  TopDom(matrix.file="/NAS1/huangliang/Hi-C/matrix_file/endosperm/20000/chr8.matrix",  window.size=10, outFile="chr8", statFilter=T)
  TopDom(matrix.file="/NAS1/huangliang/Hi-C/matrix_file/endosperm/20000/chr9.matrix",  window.size=10, outFile="chr9", statFilter=T)
  TopDom(matrix.file="/NAS1/huangliang/Hi-C/matrix_file/endosperm/20000/chr10.matrix", window.size=10, outFile="chr10", statFilter=T)

setwd("/NAS1/huangliang/Hi-C/TAD_file/endosperm/25000/")
  TopDom(matrix.file="/NAS1/huangliang/Hi-C/matrix_file/endosperm/25000/chr1.matrix",  window.size=10, outFile="chr1", statFilter=T)
  TopDom(matrix.file="/NAS1/huangliang/Hi-C/matrix_file/endosperm/25000/chr2.matrix",  window.size=10, outFile="chr2", statFilter=T)
  TopDom(matrix.file="/NAS1/huangliang/Hi-C/matrix_file/endosperm/25000/chr3.matrix",  window.size=10, outFile="chr3", statFilter=T)
  TopDom(matrix.file="/NAS1/huangliang/Hi-C/matrix_file/endosperm/25000/chr4.matrix",  window.size=10, outFile="chr4", statFilter=T)
  TopDom(matrix.file="/NAS1/huangliang/Hi-C/matrix_file/endosperm/25000/chr5.matrix",  window.size=10, outFile="chr5", statFilter=T)
  TopDom(matrix.file="/NAS1/huangliang/Hi-C/matrix_file/endosperm/25000/chr6.matrix",  window.size=10, outFile="chr6", statFilter=T)
  TopDom(matrix.file="/NAS1/huangliang/Hi-C/matrix_file/endosperm/25000/chr7.matrix",  window.size=10, outFile="chr7", statFilter=T)
  TopDom(matrix.file="/NAS1/huangliang/Hi-C/matrix_file/endosperm/25000/chr8.matrix",  window.size=10, outFile="chr8", statFilter=T)
  TopDom(matrix.file="/NAS1/huangliang/Hi-C/matrix_file/endosperm/25000/chr9.matrix",  window.size=10, outFile="chr9", statFilter=T)
  TopDom(matrix.file="/NAS1/huangliang/Hi-C/matrix_file/endosperm/25000/chr10.matrix", window.size=10, outFile="chr10", statFilter=T)

setwd("/NAS1/huangliang/Hi-C/TAD_file/endosperm/30000/")
  TopDom(matrix.file="/NAS1/huangliang/Hi-C/matrix_file/endosperm/30000/chr1.matrix",  window.size=10, outFile="chr1", statFilter=T)
  TopDom(matrix.file="/NAS1/huangliang/Hi-C/matrix_file/endosperm/30000/chr2.matrix",  window.size=10, outFile="chr2", statFilter=T)
  TopDom(matrix.file="/NAS1/huangliang/Hi-C/matrix_file/endosperm/30000/chr3.matrix",  window.size=10, outFile="chr3", statFilter=T)
  TopDom(matrix.file="/NAS1/huangliang/Hi-C/matrix_file/endosperm/30000/chr4.matrix",  window.size=10, outFile="chr4", statFilter=T)
  TopDom(matrix.file="/NAS1/huangliang/Hi-C/matrix_file/endosperm/30000/chr5.matrix",  window.size=10, outFile="chr5", statFilter=T)
  TopDom(matrix.file="/NAS1/huangliang/Hi-C/matrix_file/endosperm/30000/chr6.matrix",  window.size=10, outFile="chr6", statFilter=T)
  TopDom(matrix.file="/NAS1/huangliang/Hi-C/matrix_file/endosperm/30000/chr7.matrix",  window.size=10, outFile="chr7", statFilter=T)
  TopDom(matrix.file="/NAS1/huangliang/Hi-C/matrix_file/endosperm/30000/chr8.matrix",  window.size=10, outFile="chr8", statFilter=T)
  TopDom(matrix.file="/NAS1/huangliang/Hi-C/matrix_file/endosperm/30000/chr9.matrix",  window.size=10, outFile="chr9", statFilter=T)
  TopDom(matrix.file="/NAS1/huangliang/Hi-C/matrix_file/endosperm/30000/chr10.matrix", window.size=10, outFile="chr10", statFilter=T)

setwd("/NAS1/huangliang/Hi-C/TAD_file/endosperm/40000/")
  TopDom(matrix.file="/NAS1/huangliang/Hi-C/matrix_file/endosperm/40000/chr1.matrix",  window.size=10, outFile="chr1", statFilter=T)
  TopDom(matrix.file="/NAS1/huangliang/Hi-C/matrix_file/endosperm/40000/chr2.matrix",  window.size=10, outFile="chr2", statFilter=T)
  TopDom(matrix.file="/NAS1/huangliang/Hi-C/matrix_file/endosperm/40000/chr3.matrix",  window.size=10, outFile="chr3", statFilter=T)
  TopDom(matrix.file="/NAS1/huangliang/Hi-C/matrix_file/endosperm/40000/chr4.matrix",  window.size=10, outFile="chr4", statFilter=T)
  TopDom(matrix.file="/NAS1/huangliang/Hi-C/matrix_file/endosperm/40000/chr5.matrix",  window.size=10, outFile="chr5", statFilter=T)
  TopDom(matrix.file="/NAS1/huangliang/Hi-C/matrix_file/endosperm/40000/chr6.matrix",  window.size=10, outFile="chr6", statFilter=T)
  TopDom(matrix.file="/NAS1/huangliang/Hi-C/matrix_file/endosperm/40000/chr7.matrix",  window.size=10, outFile="chr7", statFilter=T)
  TopDom(matrix.file="/NAS1/huangliang/Hi-C/matrix_file/endosperm/40000/chr8.matrix",  window.size=10, outFile="chr8", statFilter=T)
  TopDom(matrix.file="/NAS1/huangliang/Hi-C/matrix_file/endosperm/40000/chr9.matrix",  window.size=10, outFile="chr9", statFilter=T)
  TopDom(matrix.file="/NAS1/huangliang/Hi-C/matrix_file/endosperm/40000/chr10.matrix", window.size=10, outFile="chr10", statFilter=T)

 setwd("/NAS1/huangliang/Hi-C/TAD_file/endosperm/100000/")
  TopDom(matrix.file="/NAS1/huangliang/Hi-C/matrix_file/endosperm/100000/chr1.matrix",  window.size=10, outFile="chr1", statFilter=T)
  TopDom(matrix.file="/NAS1/huangliang/Hi-C/matrix_file/endosperm/100000/chr2.matrix",  window.size=10, outFile="chr2", statFilter=T)
  TopDom(matrix.file="/NAS1/huangliang/Hi-C/matrix_file/endosperm/100000/chr3.matrix",  window.size=10, outFile="chr3", statFilter=T)
  TopDom(matrix.file="/NAS1/huangliang/Hi-C/matrix_file/endosperm/100000/chr4.matrix",  window.size=10, outFile="chr4", statFilter=T)
  TopDom(matrix.file="/NAS1/huangliang/Hi-C/matrix_file/endosperm/100000/chr5.matrix",  window.size=10, outFile="chr5", statFilter=T)
  TopDom(matrix.file="/NAS1/huangliang/Hi-C/matrix_file/endosperm/100000/chr6.matrix",  window.size=10, outFile="chr6", statFilter=T)
  TopDom(matrix.file="/NAS1/huangliang/Hi-C/matrix_file/endosperm/100000/chr7.matrix",  window.size=10, outFile="chr7", statFilter=T)
  TopDom(matrix.file="/NAS1/huangliang/Hi-C/matrix_file/endosperm/100000/chr8.matrix",  window.size=10, outFile="chr8", statFilter=T)
  TopDom(matrix.file="/NAS1/huangliang/Hi-C/matrix_file/endosperm/100000/chr9.matrix",  window.size=10, outFile="chr9", statFilter=T)
  TopDom(matrix.file="/NAS1/huangliang/Hi-C/matrix_file/endosperm/100000/chr10.matrix", window.size=10, outFile="chr10", statFilter=T)

